global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'mock-app'
    static_configs:
      - targets: ['host.docker.internal:3001']    # Reason: prometheus is run | docker container
      #- targets: ['localhost:3001']    # Reason: prometheus is run | localhost